import type { Account } from "./types";

/** Référentiel SYCEBNL complet transcrit du document fourni par MAP Afrique. */
export const MAP_AFRIQUE_ACCOUNTS: Account[] = [
  { number: "10", label: "DOTATION", source: "map" },
  { number: "101", label: "Dotation non consomptible sans droit de reprise", source: "map" },
  { number: "1011", label: "en numéraire", source: "map" },
  { number: "1015", label: "en nature", source: "map" },
  { number: "102", label: "Dotation non consomptible avec droit de reprise", source: "map" },
  { number: "1021", label: "en numéraire", source: "map" },
  { number: "1025", label: "en nature", source: "map" },
  { number: "103", label: "Droit d’entrée", source: "map" },
  { number: "104", label: "Dotation consomptible", source: "map" },
  { number: "1041", label: "Dotation consomptible", source: "map" },
  { number: "1049", label: "Dotation consomptible inscrite au compte de résultat", source: "map" },
  { number: "106", label: "Écarts de réévaluation", source: "map" },
  {
    number: "1061",
    label: "Ecarts de réévaluation sur des biens sans droit de reprise",
    source: "map",
  },
  {
    number: "10611",
    label: "Écarts de réévaluation sur des biens sans droit de reprise-immobilisations corporelles",
    source: "map",
  },
  {
    number: "10612",
    label: "Écarts de réévaluation sur des biens sans droit de reprise-immobilisations financières",
    source: "map",
  },
  {
    number: "1062",
    label: "Ecarts de réévaluation sur des biens avec droit de reprise",
    source: "map",
  },
  {
    number: "10621",
    label: "Ecarts de réévaluation sur des biens avec droit de reprise-immobilisations corporelles",
    source: "map",
  },
  {
    number: "10622",
    label: "Ecarts de réévaluation sur des biens avec droit de reprise-immobilisations financières",
    source: "map",
  },
  { number: "11", label: "RESERVES", source: "map" },
  { number: "112", label: "Réserves statutaires ou contractuelles", source: "map" },
  { number: "118", label: "Autres réserves", source: "map" },
  { number: "12", label: "REPORT A NOUVEAU", source: "map" },
  { number: "121", label: "Report à nouveau des excédents", source: "map" },
  { number: "128", label: "Résultat net en instance d’affectation", source: "map" },
  { number: "129", label: "Report à nouveau des déficits", source: "map" },
  { number: "13", label: "RÉSULTAT NET DE L’EXERCICE", source: "map" },
  { number: "131", label: "Excédent de l’exercice", source: "map" },
  { number: "139", label: "Déficit de l'exercice", source: "map" },
  { number: "14", label: "SUBVENTIONS D’INVESTISSEMENT", source: "map" },
  { number: "141", label: "Subventions d'équipement", source: "map" },
  { number: "1411", label: "Etat", source: "map" },
  { number: "1412", label: "Régions", source: "map" },
  { number: "1413", label: "Départements", source: "map" },
  { number: "1414", label: "Communes et collectivités publiques décentralisées", source: "map" },
  { number: "1415", label: "Entités publiques ou mixtes", source: "map" },
  { number: "1416", label: "Entités et organismes privés", source: "map" },
  { number: "1417", label: "Organismes internationaux", source: "map" },
  { number: "1418", label: "Autres", source: "map" },
  { number: "148", label: "Autres subventions d’investissement", source: "map" },
  { number: "15", label: "PROVISIONS RÉGLEMENTÉES ET FONDS ASSIMILÉS", source: "map" },
  { number: "154", label: "Provisions spéciales de réévaluation", source: "map" },
  { number: "158", label: "Autres provisions réglementées et fonds assimilés", source: "map" },
  {
    number: "16",
    label: "FONDS AFFECTÉS ET PROVENANT DE DONS OU LEGS D’IMMOBILISATIONS",
    source: "map",
  },
  {
    number: "161",
    label: "Fonds projet de développement — avances de fonds à justifier",
    source: "map",
  },
  {
    number: "162",
    label: "Fonds affectés aux investissements du projet de développement - bailleurs de fonds",
    source: "map",
  },
  {
    number: "163",
    label: "Fonds affectés aux investissements du projet de développement - l’État",
    source: "map",
  },
  {
    number: "164",
    label: "Fonds affectés aux investissements des autres organismes de financement assimilés",
    source: "map",
  },
  { number: "165", label: "Fonds affectés à un projet spécifique", source: "map" },
  { number: "167", label: "Fonds provenant de dons et legs d’immobilisations", source: "map" },
  { number: "1671", label: "affectés", source: "map" },
  { number: "1672", label: "non affectés", source: "map" },
  { number: "1679", label: "Engagements auprès donateur", source: "map" },
  { number: "168", label: "Autres fonds affectés", source: "map" },
  { number: "169", label: "Fonds affectés à recevoir", source: "map" },
  { number: "17", label: "FONDS REPORTÉS", source: "map" },
  { number: "171", label: "Donation temporaire d’usufruit", source: "map" },
  {
    number: "172",
    label: "Donations et legs non encore reçus d’immobilisations destinées à la vente",
    source: "map",
  },
  { number: "178", label: "Autres fonds reportés", source: "map" },
  { number: "18", label: "EMPRUNTS ET DETTES ASSIMILÉES", source: "map" },
  { number: "181", label: "Emprunts obligataires", source: "map" },
  { number: "182", label: "Emprunts et dettes auprès des établissements de crédit", source: "map" },
  { number: "183", label: "Avances reçues de l’État", source: "map" },
  { number: "185", label: "Dépôts et cautionnements reçus", source: "map" },
  { number: "1851", label: "Dépôts", source: "map" },
  { number: "1852", label: "Cautionnements", source: "map" },
  { number: "186", label: "Intérêts courus", source: "map" },
  { number: "1861", label: "sur emprunts obligataires", source: "map" },
  {
    number: "1862",
    label: "sur emprunts et dettes auprès des établissements de crédit",
    source: "map",
  },
  { number: "1863", label: "sur avances reçues de l'État", source: "map" },
  { number: "1865", label: "sur dépôts et cautionnements reçus", source: "map" },
  { number: "1868", label: "sur autres emprunts et dettes", source: "map" },
  { number: "187", label: "Dettes de location-acquisition", source: "map" },
  {
    number: "1871",
    label: "Dettes de location-acquisition / crédit-bail immobilier",
    source: "map",
  },
  { number: "1872", label: "Dettes de location-acquisition / crédit-bail mobilier", source: "map" },
  { number: "1873", label: "Dettes de location-acquisition / location-vente", source: "map" },
  { number: "1876", label: "Intérêts courus", source: "map" },
  { number: "188", label: "Autres emprunts et dettes", source: "map" },
  { number: "19", label: "PROVISIONS POUR RISQUES ET CHARGES", source: "map" },
  { number: "191", label: "Provisions pour litiges", source: "map" },
  { number: "194", label: "Provisions pour pertes de change", source: "map" },
  { number: "196", label: "Provisions pour pensions et obligations similaires", source: "map" },
  { number: "198", label: "Autres provisions pour risques et charges", source: "map" },
  { number: "1981", label: "Provisions pour amendes et pénalités", source: "map" },
  { number: "1984", label: "Provisions pour démantèlement et remise en état", source: "map" },
  { number: "1988", label: "Provisions pour divers risques et charges", source: "map" },
  {
    number: "20",
    label:
      "IMMOBILISATIONS DESTINÉES À LA VENTE PROVENANT DE DONS ET LEGS NON ENCORE REÇUS ET USUFRUIT TEMPORAIRE",
    source: "map",
  },
  { number: "201", label: "Immobilisations incorporelles", source: "map" },
  { number: "2011", label: "Usufruit temporaire", source: "map" },
  { number: "2012", label: "Brevets, licences, concessions et droits similaires", source: "map" },
  { number: "2013", label: "Logiciels et sites internet", source: "map" },
  { number: "2014", label: "Marques", source: "map" },
  { number: "2017", label: "Autres", source: "map" },
  { number: "202", label: "Terrains", source: "map" },
  { number: "203", label: "Bâtiments", source: "map" },
  { number: "204", label: "Matériels", source: "map" },
  { number: "205", label: "Titres de participations", source: "map" },
  { number: "21", label: "IMMOBILISATIONS INCORPORELLES", source: "map" },
  { number: "212", label: "Brevets, licences, concessions et droits similaires", source: "map" },
  { number: "2121", label: "Brevets", source: "map" },
  { number: "2122", label: "Licences", source: "map" },
  { number: "2123", label: "Concessions de service public", source: "map" },
  { number: "2128", label: "Autres concessions et droits similaires", source: "map" },
  { number: "213", label: "Logiciels et sites internet", source: "map" },
  { number: "2131", label: "Logiciels", source: "map" },
  { number: "2132", label: "Sites internet", source: "map" },
  { number: "214", label: "Marques", source: "map" },
  { number: "218", label: "Autres droits et valeurs incorporels", source: "map" },
  { number: "2181", label: "Indemnités de transfert aux joueurs", source: "map" },
  { number: "219", label: "Immobilisations incorporelles en cours", source: "map" },
  { number: "2193", label: "Logiciels et sites internet", source: "map" },
  { number: "2198", label: "Autres droits et valeurs incorporels", source: "map" },
  { number: "22", label: "TERRAINS", source: "map" },
  { number: "221", label: "Terrains agricoles et forestiers", source: "map" },
  { number: "2211", label: "Terrains d'exploitation agricole", source: "map" },
  { number: "2212", label: "Terrains d'exploitation forestière", source: "map" },
  { number: "2218", label: "Autres terrains", source: "map" },
  { number: "222", label: "Terrains nus", source: "map" },
  { number: "2221", label: "Terrains à bâtir", source: "map" },
  { number: "2228", label: "Autres terrains nus", source: "map" },
  { number: "223", label: "Terrains bâtis", source: "map" },
  { number: "2231", label: "pour bâtiments industriels et agricoles", source: "map" },
  { number: "2232", label: "pour bâtiments administratifs et commerciaux", source: "map" },
  {
    number: "2234",
    label: "pour bâtiments affectés aux autres opérations professionnelles",
    source: "map",
  },
  {
    number: "2235",
    label: "pour bâtiments affectés aux autres opérations non professionnelles",
    source: "map",
  },
  { number: "2238", label: "Autres terrains bâtis", source: "map" },
  { number: "224", label: "Travaux de mise en valeur des terrains", source: "map" },
  { number: "2241", label: "Plantation d’arbres et d’arbustes", source: "map" },
  { number: "2245", label: "Améliorations du fonds", source: "map" },
  { number: "2248", label: "Autres travaux", source: "map" },
  { number: "226", label: "Terrains aménagés", source: "map" },
  { number: "2261", label: "Parkings", source: "map" },
  { number: "228", label: "Autres terrains", source: "map" },
  { number: "2281", label: "Terrains - immeubles de placement", source: "map" },
  { number: "2285", label: "Terrains des logements affectés au personnel", source: "map" },
  { number: "2286", label: "Terrains de location - acquisition", source: "map" },
  { number: "2288", label: "Divers terrains", source: "map" },
  { number: "229", label: "Aménagements de terrains en cours", source: "map" },
  { number: "2291", label: "Terrains agricoles et forestiers", source: "map" },
  { number: "2292", label: "Terrains nus", source: "map" },
  { number: "2298", label: "Autres terrains", source: "map" },
  { number: "23", label: "BÂTIMENTS, INSTALLATIONS TECHNIQUES ET AGENCEMENTS", source: "map" },
  {
    number: "231",
    label:
      "Bâtiments industriels, agricoles, administratifs, commerciaux, religieux et autres sur sol propre",
    source: "map",
  },
  { number: "2311", label: "Bâtiments industriels", source: "map" },
  { number: "2312", label: "Bâtiments agricoles", source: "map" },
  { number: "2313", label: "Bâtiments administratifs et commerciaux", source: "map" },
  { number: "2314", label: "Bâtiments affectés au logement du personnel", source: "map" },
  { number: "2315", label: "Bâtiments - immeubles de placement", source: "map" },
  { number: "2316", label: "Bâtiments de location - acquisition", source: "map" },
  { number: "2317", label: "Edifices religieux et assimilés", source: "map" },
  { number: "2318", label: "Autres bâtiments sur sol propre", source: "map" },
  {
    number: "232",
    label:
      "Bâtiments industriels, agricoles, administratifs, commerciaux, religieux et autres sur sol d’autrui",
    source: "map",
  },
  { number: "2321", label: "Bâtiments industriels", source: "map" },
  { number: "2322", label: "Bâtiments agricoles", source: "map" },
  { number: "2323", label: "Bâtiments administratifs et commerciaux", source: "map" },
  { number: "2324", label: "Bâtiments affectés au logement du personnel", source: "map" },
  { number: "2325", label: "Bâtiments - immeubles de placement", source: "map" },
  { number: "2326", label: "Bâtiments de location - acquisition", source: "map" },
  { number: "2327", label: "Edifices religieux et assimilés", source: "map" },
  { number: "2328", label: "Autres bâtiments sur sol d'autrui", source: "map" },
  { number: "233", label: "Ouvrages d'infrastructure", source: "map" },
  { number: "2331", label: "Voies de terre", source: "map" },
  { number: "2332", label: "Voies de fer", source: "map" },
  { number: "2333", label: "Voies d’eau", source: "map" },
  { number: "2334", label: "Barrages, digues", source: "map" },
  { number: "2335", label: "Pistes d’aérodrome", source: "map" },
  { number: "2337", label: "Stades et autres infrastructures sportives", source: "map" },
  { number: "2338", label: "Autres ouvrages d’infrastructures", source: "map" },
  { number: "234", label: "Aménagements, agencements et installations techniques", source: "map" },
  { number: "2341", label: "Installations complexes spécialisées sur sol propre", source: "map" },
  { number: "2342", label: "Installations complexes spécialisées sur sol d'autrui", source: "map" },
  { number: "2343", label: "Installations à caractère spécifique sur sol propre", source: "map" },
  { number: "2344", label: "Installations à caractère spécifique sur sol d’autrui", source: "map" },
  { number: "2345", label: "Aménagements et agencements des bâtiments", source: "map" },
  { number: "235", label: "Aménagements de bureaux et assimilés", source: "map" },
  { number: "2351", label: "Installations générales", source: "map" },
  { number: "2358", label: "Autres aménagements de bureaux", source: "map" },
  { number: "238", label: "Autres installations et agencements", source: "map" },
  {
    number: "2381",
    label: "Autres installations et agencements des édifices religieux et assimilés",
    source: "map",
  },
  {
    number: "2382",
    label: "Autres installations et agencements des stades et autres infrastructures sportives",
    source: "map",
  },
  {
    number: "239",
    label: "Bâtiments, aménagements, agencements et installations en cours",
    source: "map",
  },
  { number: "2391", label: "Bâtiments sur sol propre en cours", source: "map" },
  { number: "2392", label: "Bâtiments sur sol d'autrui en cours", source: "map" },
  { number: "2393", label: "Ouvrages d'infrastructure en cours", source: "map" },
  {
    number: "2394",
    label: "Aménagements, agencements et installations techniques en cours",
    source: "map",
  },
  { number: "2395", label: "Aménagements de bureaux en cours", source: "map" },
  { number: "2396", label: "Bâtiments en cours-immeubles de placement", source: "map" },
  { number: "2398", label: "Autres installations et agencements en cours", source: "map" },
  { number: "24", label: "MATERIEL, MOBILIER ET ACTIFS BIOLOGIQUES", source: "map" },
  { number: "241", label: "Matériel et outillage industriel et commercial", source: "map" },
  { number: "2411", label: "Matériel industriel", source: "map" },
  { number: "2412", label: "Outillage industriel", source: "map" },
  { number: "2413", label: "Matériel commercial", source: "map" },
  { number: "2414", label: "Outillage commercial", source: "map" },
  {
    number: "2416",
    label: "Matériel et outillage industriel et commercial de location — acquisition",
    source: "map",
  },
  { number: "242", label: "Matériel et outillage agricole", source: "map" },
  { number: "2421", label: "Matériel agricole", source: "map" },
  { number: "2422", label: "Outillage agricole", source: "map" },
  {
    number: "2426",
    label: "Matériel et outillage agricole de location-acquisition",
    source: "map",
  },
  { number: "243", label: "Matériel d'emballage récupérable et identifiable", source: "map" },
  { number: "244", label: "Matériel et mobilier", source: "map" },
  { number: "2441", label: "Matériel et mobilier de bureau", source: "map" },
  { number: "2442", label: "Matériel informatique et bureautique", source: "map" },
  { number: "2443", label: "Matériel et mobilier religieux", source: "map" },
  { number: "2444", label: "Matériel et mobilier sportifs", source: "map" },
  { number: "2445", label: "Matériel et mobilier - immeubles de placement", source: "map" },
  { number: "2446", label: "Matériel et mobilier de location - acquisition", source: "map" },
  { number: "2447", label: "Matériel et mobilier des logements du personnel", source: "map" },
  { number: "245", label: "Matériel de transport", source: "map" },
  { number: "2451", label: "Matériel automobile", source: "map" },
  { number: "2452", label: "Matériel ferroviaire", source: "map" },
  { number: "2453", label: "Matériel fluvial, lagunaire", source: "map" },
  { number: "2454", label: "Matériel naval", source: "map" },
  { number: "2455", label: "Matériel aérien", source: "map" },
  { number: "2456", label: "Matériel de transport de location - acquisition", source: "map" },
  { number: "2457", label: "Matériel hippomobile", source: "map" },
  { number: "2458", label: "Autres matériels de transport", source: "map" },
  { number: "246", label: "Actifs biologiques", source: "map" },
  { number: "2461", label: "Cheptel, animaux de trait", source: "map" },
  { number: "2462", label: "Cheptel, animaux reproducteurs", source: "map" },
  { number: "2463", label: "Animaux de garde", source: "map" },
  { number: "2465", label: "Plantations agricoles", source: "map" },
  { number: "2468", label: "Autres actifs biologiques", source: "map" },
  {
    number: "247",
    label: "Agencements, aménagements du matériel et des actifs biologiques",
    source: "map",
  },
  { number: "2471", label: "Agencements et aménagements du matériel", source: "map" },
  { number: "2472", label: "Agencements et aménagements des actifs biologiques", source: "map" },
  {
    number: "2478",
    label: "Autres agencements, aménagements du matériel et des actifs biologiques",
    source: "map",
  },
  { number: "248", label: "Autres matériels et mobiliers", source: "map" },
  { number: "2481", label: "Collections et œuvres d'art", source: "map" },
  { number: "2488", label: "Divers matériels et mobiliers", source: "map" },
  { number: "249", label: "Matériels et actifs biologiques en cours", source: "map" },
  { number: "2491", label: "Matériel et outillage industriel et commercial", source: "map" },
  { number: "2492", label: "Matériel et outillage agricole", source: "map" },
  { number: "2493", label: "Matériel d'emballage récupérable et identifiable", source: "map" },
  { number: "2494", label: "Matériel et mobilier de bureau", source: "map" },
  { number: "2495", label: "Matériel de transport", source: "map" },
  { number: "2496", label: "Actifs biologiques", source: "map" },
  {
    number: "2497",
    label: "Agencements et aménagements du matériel et des actifs biologiques",
    source: "map",
  },
  { number: "2498", label: "Autres matériels et actifs biologiques", source: "map" },
  { number: "25", label: "AVANCES ET ACOMPTES VERSÉS SUR IMMOBILISATIONS", source: "map" },
  {
    number: "251",
    label: "Avances et acomptes versés sur immobilisations incorporelles",
    source: "map",
  },
  {
    number: "252",
    label: "Avances et acomptes versés sur immobilisations corporelles",
    source: "map",
  },
  { number: "26", label: "TITRES DE PARTICIPATION", source: "map" },
  { number: "261", label: "Titres de participation", source: "map" },
  { number: "265", label: "Participations dans des organismes professionnels", source: "map" },
  {
    number: "266",
    label: "Parts dans des groupements d’intérêt économique (G.LE.)",
    source: "map",
  },
  { number: "268", label: "Autres titres de participation", source: "map" },
  { number: "27", label: "AUTRES IMMOBLISATIONS FINANCIÈRES", source: "map" },
  { number: "271", label: "Prêts et créances", source: "map" },
  { number: "2711", label: "Prêts participatifs", source: "map" },
  { number: "2713", label: "Billets de fonds", source: "map" },
  { number: "2715", label: "Titres prêtés", source: "map" },
  { number: "2718", label: "Autres prêts et créances", source: "map" },
  { number: "272", label: "Prêts au personnel", source: "map" },
  { number: "2721", label: "Prêts immobiliers", source: "map" },
  { number: "2722", label: "Prêts mobiliers et d'installation", source: "map" },
  { number: "2728", label: "Autres prêts au personnel", source: "map" },
  { number: "273", label: "Créances sur l'Etat", source: "map" },
  { number: "2731", label: "Retenues de garantie", source: "map" },
  { number: "2733", label: "Fonds réglementé", source: "map" },
  { number: "2738", label: "Autres créances sur l'Etat", source: "map" },
  { number: "274", label: "Titres immobilisés", source: "map" },
  {
    number: "2741",
    label: "Titres immobilisés de l’activité de portefeuille (T.L.A.P.)",
    source: "map",
  },
  { number: "2742", label: "Titres participatifs", source: "map" },
  { number: "2743", label: "Certificats d'investissement", source: "map" },
  { number: "2744", label: "Parts de fonds commun de placement (F.C.P.)", source: "map" },
  { number: "2745", label: "Obligations", source: "map" },
  { number: "2748", label: "Autres titres immobilisés", source: "map" },
  { number: "275", label: "Dépôts et cautionnements versés", source: "map" },
  { number: "2751", label: "Dépôts pour loyers d'avance", source: "map" },
  { number: "2752", label: "Dépôts pour l'électricité", source: "map" },
  { number: "2753", label: "Dépôts pour l’eau", source: "map" },
  { number: "2754", label: "Dépôts pour le gaz", source: "map" },
  { number: "2755", label: "Dépôts pour le téléphone, la télécopie", source: "map" },
  { number: "2758", label: "Autres dépôts et cautionnement", source: "map" },
  { number: "276", label: "Intérêts courus", source: "map" },
  { number: "2761", label: "Prêts et créances", source: "map" },
  { number: "2762", label: "Prêts au personnel", source: "map" },
  { number: "2763", label: "Créances sur l’État", source: "map" },
  { number: "2764", label: "Titres immobilisés", source: "map" },
  { number: "2765", label: "Dépôts et cautionnements versés", source: "map" },
  { number: "2768", label: "Immobilisations financières diverses", source: "map" },
  { number: "278", label: "Immobilisations financières diverses", source: "map" },
  { number: "2781", label: "Créances diverses", source: "map" },
  { number: "2784", label: "Banques dépôts à terme et opérations assimilées", source: "map" },
  { number: "2785", label: "Or et métaux précieux", source: "map" },
  { number: "2788", label: "Autres immobilisations financières", source: "map" },
  { number: "28", label: "AMORTISSEMENTS", source: "map" },
  { number: "280", label: "Amortissements d'usufruit temporaire", source: "map" },
  { number: "281", label: "Amortissements des immobilisations incorporelles", source: "map" },
  {
    number: "2812",
    label: "Amortissements des brevets, licences, concessions et droits similaires",
    source: "map",
  },
  { number: "2813", label: "Amortissements des logiciels et sites internet", source: "map" },
  { number: "2814", label: "Amortissements des marques", source: "map" },
  {
    number: "2817",
    label: "Amortissements des Indemnités de transfert aux joueurs",
    source: "map",
  },
  {
    number: "2818",
    label: "Amortissements des autres droits et valeurs incorporels",
    source: "map",
  },
  { number: "282", label: "Amortissements des terrains", source: "map" },
  {
    number: "2824",
    label: "Amortissements des travaux de mise en valeur des terrains",
    source: "map",
  },
  {
    number: "283",
    label: "Amortissements des bâtiments, installations techniques et agencements",
    source: "map",
  },
  {
    number: "2831",
    label:
      "Amortissements des bâtiments industriels, agricoles, administratifs, commerciaux, religieux et autres sur sol propre",
    source: "map",
  },
  {
    number: "2832",
    label:
      "Amortissements des bâtiments industriels, agricoles, administratifs, commerciaux, religieux et autres sur sol d’autrui",
    source: "map",
  },
  { number: "2833", label: "Amortissements des ouvrages d'infrastructure", source: "map" },
  {
    number: "2834",
    label: "Amortissements des aménagements, agencements et installations techniques",
    source: "map",
  },
  { number: "2835", label: "Amortissements des aménagements de bureaux", source: "map" },
  {
    number: "2838",
    label: "Amortissements des autres installations et agencements",
    source: "map",
  },
  { number: "284", label: "Amortissements du matériel", source: "map" },
  {
    number: "2841",
    label: "Amortissements du matériel et de l'outillage industriel et commercial",
    source: "map",
  },
  { number: "2842", label: "Amortissements du matériel et de l'outillage agricole", source: "map" },
  {
    number: "2843",
    label: "Amortissements du matériel d'emballage récupérable et identifiable",
    source: "map",
  },
  { number: "2844", label: "Amortissements du matériel et du mobilier", source: "map" },
  { number: "2845", label: "Amortissements du matériel de transport", source: "map" },
  { number: "2846", label: "Amortissements des actifs biologiques", source: "map" },
  {
    number: "2847",
    label: "Amortissements des agencements et aménagements du matériel et des actifs biologiques",
    source: "map",
  },
  { number: "2848", label: "Amortissements des autres matériels", source: "map" },
  { number: "29", label: "DEPRECIATIONS DES IMMOBILISATIONS", source: "map" },
  {
    number: "290",
    label:
      "Dépréciations des immobilisations destinées à la vente provenant de dons et legs non encore reçus et d’usufruit temporaire",
    source: "map",
  },
  { number: "2901", label: "Dépréciations d’usufruit temporaire", source: "map" },
  {
    number: "2902",
    label:
      "Dépréciations des immobilisations destinées à la vente provenant de dons et legs non encore reçus",
    source: "map",
  },
  { number: "291", label: "Dépréciations des immobilisations incorporelles", source: "map" },
  {
    number: "2912",
    label: "Dépréciations des brevets, licences, concessions et droits similaires",
    source: "map",
  },
  { number: "2913", label: "Dépréciations des logiciels et sites internet", source: "map" },
  { number: "2914", label: "Dépréciations des marques", source: "map" },
  {
    number: "2918",
    label: "Dépréciations des autres droits et valeurs incorporels",
    source: "map",
  },
  {
    number: "2919",
    label: "Dépréciations des immobilisations incorporelles en cours",
    source: "map",
  },
  { number: "292", label: "Dépréciations des terrains", source: "map" },
  { number: "2921", label: "Dépréciations des terrains agricoles et forestiers", source: "map" },
  { number: "2922", label: "Dépréciations des terrains nus", source: "map" },
  { number: "2923", label: "Dépréciations des terrains bâtis", source: "map" },
  {
    number: "2924",
    label: "Dépréciations des travaux de mise en valeur des terrains",
    source: "map",
  },
  { number: "2926", label: "Dépréciations des terrains aménagés", source: "map" },
  { number: "2928", label: "Dépréciations des autres terrains", source: "map" },
  { number: "2929", label: "Dépréciations des aménagements de terrains en cours", source: "map" },
  {
    number: "293",
    label: "Dépréciations des bâtiments, installations techniques et agencements",
    source: "map",
  },
  {
    number: "2931",
    label:
      "Dépréciations des bâtiments industriels, agricoles, administratifs, commerciaux, religieux et autres sur sol propre",
    source: "map",
  },
  {
    number: "2932",
    label:
      "Dépréciations des bâtiments industriels, agricoles, administratifs, commerciaux, religieux et autres sur sol d’autrui",
    source: "map",
  },
  { number: "2933", label: "Dépréciations des ouvrages d’infrastructures", source: "map" },
  {
    number: "2934",
    label: "Dépréciations des aménagements, agencements et installations techniques",
    source: "map",
  },
  { number: "2935", label: "Dépréciations des aménagements de bureaux", source: "map" },
  { number: "2938", label: "Dépréciations des autres installations et agencements", source: "map" },
  { number: "2939", label: "Dépréciations des bâtiments et installations en cours", source: "map" },
  {
    number: "294",
    label: "Dépréciations de matériel, du mobilier et de l’actif biologique",
    source: "map",
  },
  {
    number: "2941",
    label: "Dépréciations du matériel et de l'outillage industriel et commercial",
    source: "map",
  },
  { number: "2942", label: "Dépréciations du matériel et de l'outillage agricole", source: "map" },
  {
    number: "2943",
    label: "Dépréciations du matériel d’emballage récupérable et identifiable",
    source: "map",
  },
  { number: "2944", label: "Dépréciations du matériel et du mobilier", source: "map" },
  { number: "2945", label: "Dépréciations du matériel de transport", source: "map" },
  { number: "2946", label: "Dépréciations des actifs biologiques", source: "map" },
  {
    number: "2947",
    label: "Dépréciations des aménagements et agencements du matériel et des actifs biologiques",
    source: "map",
  },
  { number: "2948", label: "Dépréciations des autres matériels", source: "map" },
  { number: "2949", label: "Dépréciations de matériel en cours", source: "map" },
  {
    number: "295",
    label: "Dépréciations des avances et acomptes versés sur immobilisations",
    source: "map",
  },
  {
    number: "2951",
    label: "Dépréciations des avances et acomptes versés sur immobilisations incorporelles",
    source: "map",
  },
  {
    number: "2952",
    label: "Dépréciations des avances et acomptes versés sur immobilisations corporelles",
    source: "map",
  },
  { number: "296", label: "Dépréciations des titres de participation", source: "map" },
  { number: "2961", label: "Dépréciations des titres de participation", source: "map" },
  {
    number: "2965",
    label: "Dépréciations des participations dans des organismes professionnels",
    source: "map",
  },
  { number: "2966", label: "Dépréciations des parts dans des GIE", source: "map" },
  { number: "2968", label: "Dépréciations des autres titres de participation", source: "map" },
  { number: "297", label: "Dépréciations des autres immobilisations financières", source: "map" },
  { number: "2971", label: "Dépréciations des prêts et créances", source: "map" },
  { number: "2972", label: "Dépréciations des prêts au personnel", source: "map" },
  { number: "2973", label: "Dépréciations des créances sur l’État", source: "map" },
  { number: "2974", label: "Dépréciations des titres immobilisés", source: "map" },
  { number: "2975", label: "Dépréciations des dépôts et cautionnements versés", source: "map" },
  {
    number: "2977",
    label: "Dépréciations des créances rattachées à des participations et avances à des GIE",
    source: "map",
  },
  { number: "2978", label: "Dépréciations des créances financières diverses", source: "map" },
  { number: "31", label: "BIENS LIES A L'ACTIVITÉ", source: "map" },
  { number: "311", label: "Biens liés à l’activité A", source: "map" },
  { number: "312", label: "Biens liés à l’activité B", source: "map" },
  { number: "32", label: "MARCHANDISES, MATIÈRES PREMIÈRES ET FOURNITURES LIEES", source: "map" },
  { number: "321", label: "Marchandises A", source: "map" },
  { number: "322", label: "Marchandises B", source: "map" },
  { number: "323", label: "Matières A", source: "map" },
  { number: "324", label: "Matières B", source: "map" },
  { number: "325", label: "Fournitures liées (A, B)", source: "map" },
  { number: "33", label: "AUTRES APPROVISIONNEMENTS", source: "map" },
  { number: "331", label: "Matières consommables", source: "map" },
  { number: "333", label: "Fournitures de magasin", source: "map" },
  { number: "334", label: "Fournitures de bureau", source: "map" },
  { number: "335", label: "Emballages", source: "map" },
  { number: "3351", label: "Emballages perdus", source: "map" },
  { number: "3352", label: "Emballages récupérables non identifiables", source: "map" },
  { number: "3353", label: "Emballages à usage mixte", source: "map" },
  { number: "3358", label: "Autres emballages", source: "map" },
  { number: "338", label: "Autres matières", source: "map" },
  { number: "34", label: "DONS EN NATURE", source: "map" },
  { number: "341", label: "Dons en nature non affectés", source: "map" },
  { number: "345", label: "Dons en nature affectés", source: "map" },
  { number: "35", label: "PRODUITS ET SERVICES EN COURS", source: "map" },
  { number: "36", label: "PRODUITS FINIS, PRODUITS INTERMÉDIAIRES ET RÉSIDUELS", source: "map" },
  { number: "361", label: "Produits finis A", source: "map" },
  { number: "362", label: "Produits finis B", source: "map" },
  { number: "363", label: "Actifs biologiques", source: "map" },
  { number: "3631", label: "Animaux", source: "map" },
  { number: "3632", label: "Végétaux", source: "map" },
  { number: "3638", label: "Autres stocks (activités annexes)", source: "map" },
  { number: "367", label: "Produits intermédiaires et résiduels", source: "map" },
  { number: "37", label: "STOCKS EN COURS DE ROUTE, EN CONSIGNATION OU EN DÉPÔT", source: "map" },
  { number: "371", label: "Biens liés à l’activité en cours de route", source: "map" },
  {
    number: "372",
    label: "Marchandises, matières premières et fournitures liés en cours de route",
    source: "map",
  },
  { number: "373", label: "Autres approvisionnements en cours de route", source: "map" },
  { number: "376", label: "Produits finis en cours de route", source: "map" },
  { number: "377", label: "Stocks en consignation ou en dépôt", source: "map" },
  { number: "3771", label: "Stock en consignation", source: "map" },
  { number: "3772", label: "Stock en dépôt", source: "map" },
  {
    number: "378",
    label: "Stock provenant d’immobilisations mises hors services ou au rebut",
    source: "map",
  },
  { number: "38", label: "DONS EN NATURE HAO", source: "map" },
  { number: "381", label: "non affectés", source: "map" },
  { number: "385", label: "affectés", source: "map" },
  { number: "39", label: "DÉPRÉCIATIONS DES STOCKS ET DES PRODUCTIONS EN COURS", source: "map" },
  { number: "391", label: "Dépréciations des stocks de biens liés à l’activité", source: "map" },
  {
    number: "392",
    label: "Dépréciations des stocks de marchandises, et matières premières et fournitures liées",
    source: "map",
  },
  { number: "393", label: "Dépréciations des stocks d’autres approvisionnements", source: "map" },
  {
    number: "396",
    label: "Dépréciations des stocks de produits finis, produits intermédiaires et résiduels",
    source: "map",
  },
  {
    number: "397",
    label: "Dépréciations des stocks en cours de route, en consignation ou en dépôt",
    source: "map",
  },
  { number: "40", label: "FOURNISSEURS ET COMPTES RATTACHES", source: "map" },
  { number: "401", label: "Fournisseurs, dettes en compte", source: "map" },
  { number: "4011", label: "Fournisseurs", source: "map" },
  { number: "4013", label: "Fournisseurs sous-traitants", source: "map" },
  { number: "4016", label: "Fournisseurs, réserve de propriété", source: "map" },
  { number: "4017", label: "Fournisseurs, retenues de garantie", source: "map" },
  { number: "402", label: "Fournisseurs, effets à payer", source: "map" },
  { number: "4021", label: "Fournisseurs, effets à payer", source: "map" },
  { number: "4023", label: "Fournisseurs sous-traitants, effets à payer", source: "map" },
  { number: "408", label: "Fournisseurs, factures non parvenues", source: "map" },
  { number: "4081", label: "Fournisseurs", source: "map" },
  { number: "4083", label: "Fournisseurs sous-traitants", source: "map" },
  { number: "4086", label: "Fournisseurs, intérêts courus", source: "map" },
  { number: "409", label: "Fournisseurs débiteurs", source: "map" },
  { number: "4091", label: "Fournisseurs avances et acomptes versés", source: "map" },
  {
    number: "4093",
    label: "Fournisseurs sous-traitants avances et acomptes versés",
    source: "map",
  },
  {
    number: "4094",
    label: "Fournisseurs créances pour emballages et matériels à rendre",
    source: "map",
  },
  {
    number: "4098",
    label: "Fournisseurs, rabais, remises, ristournes et autres avoirs à obtenir",
    source: "map",
  },
  { number: "41", label: "ADHERENTS, CLIENTS-USAGERS ET COMPTES RATTACHÉS", source: "map" },
  { number: "411", label: "Adhérents", source: "map" },
  { number: "412", label: "Clients-usagers", source: "map" },
  {
    number: "413",
    label: "Adhérents, Clients-usagers, chèques, effets et autres valeurs impayés",
    source: "map",
  },
  { number: "4131", label: "Adhérents, chèques impayés", source: "map" },
  { number: "4132", label: "Clients-usagers, chèques impayés", source: "map" },
  { number: "4133", label: "Adhérents, Autres valeurs impayées", source: "map" },
  { number: "4138", label: "Clients-usagers, autres valeurs impayées", source: "map" },
  {
    number: "416",
    label: "Créances, adhérents, clients-usagers litigieuses ou douteuses",
    source: "map",
  },
  { number: "4161", label: "Adhérents cotisations litigieuses ou douteuses", source: "map" },
  { number: "4162", label: "Créances litigieuses ou douteuses", source: "map" },
  { number: "418", label: "Adhérents, clients-usagers produits à recevoir", source: "map" },
  { number: "4181", label: "Adhérents, appels de fonds à établir", source: "map" },
  { number: "4182", label: "Clients- usagers, factures à établir", source: "map" },
  { number: "4186", label: "Adherents, Clients-usagers, intéréts courus", source: "map" },
  { number: "419", label: "Adhérents, Clients-usagers créditeurs", source: "map" },
  { number: "4191", label: "Adhérents, avances reçues", source: "map" },
  { number: "4192", label: "Clients-usagers, avances et acomptes reçus", source: "map" },
  {
    number: "4194",
    label: "Clients-usagers, dettes pour emballages et matériels consignés",
    source: "map",
  },
  {
    number: "4198",
    label: "Clients-usagers, rabais, remises, ristournes et autres avoirs à accorder",
    source: "map",
  },
  { number: "42", label: "PERSONNEL", source: "map" },
  { number: "421", label: "Personnel, avances et acomptes", source: "map" },
  { number: "4211", label: "Personnel, avances", source: "map" },
  { number: "4212", label: "Personnel, acomptes", source: "map" },
  { number: "4213", label: "Frais avancés et fournitures au personnel", source: "map" },
  { number: "422", label: "Personnel, rémunérations dues", source: "map" },
  { number: "423", label: "Personnel, oppositions, saisies arrêts", source: "map" },
  { number: "4231", label: "Personnel, oppositions", source: "map" },
  { number: "4232", label: "Personnel, saisies arrêts", source: "map" },
  { number: "4233", label: "Personnel, avis à tiers détenteur", source: "map" },
  { number: "424", label: "Personnel, œuvres sociales internes", source: "map" },
  { number: "4241", label: "Assistance médicale", source: "map" },
  { number: "4242", label: "Allocations familiales", source: "map" },
  { number: "4245", label: "Organismes sociaux rattachés à l'entité", source: "map" },
  { number: "4248", label: "Autres œuvres sociales internes", source: "map" },
  { number: "425", label: "Représentants du personnel", source: "map" },
  { number: "4251", label: "Délégués du personnel", source: "map" },
  { number: "4252", label: "Syndicats et assimilés", source: "map" },
  { number: "4258", label: "Autres représentants du personnel", source: "map" },
  { number: "427", label: "Personnel — dépôts", source: "map" },
  { number: "428", label: "Personnel, charges à payer et produits à recevoir", source: "map" },
  { number: "4281", label: "Personnel congés à payer", source: "map" },
  { number: "4286", label: "Autres Charges à payer", source: "map" },
  { number: "4287", label: "Produits à recevoir", source: "map" },
  { number: "43", label: "ORGANISMES SOCIAUX", source: "map" },
  { number: "431", label: "Sécurité sociale", source: "map" },
  { number: "4311", label: "Prestations familiales", source: "map" },
  { number: "4312", label: "Accidents de travail", source: "map" },
  { number: "4318", label: "Autres cotisations sociales", source: "map" },
  { number: "432", label: "Caisses de retraite", source: "map" },
  { number: "4321", label: "Caisse de retraite obligatoire", source: "map" },
  { number: "4322", label: "Caisse de retraite complémentaire", source: "map" },
  { number: "4328", label: "Autres caisses de retraites", source: "map" },
  { number: "433", label: "Autres organismes sociaux", source: "map" },
  { number: "4331", label: "Mutuelle de santé", source: "map" },
  { number: "4332", label: "Assurances retraite", source: "map" },
  { number: "4333", label: "Assurances et organismes de santé", source: "map" },
  {
    number: "438",
    label: "Organismes sociaux, charges à payer et produits à recevoir",
    source: "map",
  },
  { number: "4381", label: "Charges sociales sur gratifications à payer", source: "map" },
  { number: "4382", label: "Charges sociales sur congés à payer", source: "map" },
  { number: "4386", label: "Autres charges à payer", source: "map" },
  { number: "4387", label: "Produits à recevoir", source: "map" },
  { number: "44", label: "ÉTAT ET COLLECTIVITÉS PUBLIQUES", source: "map" },
  { number: "442", label: "État, autres impôts et taxes", source: "map" },
  { number: "4422", label: "Impôts et taxes pour les collectivités publiques", source: "map" },
  { number: "4423", label: "Impôts et taxes recouvrables sur des obligataires", source: "map" },
  {
    number: "4424",
    label: "Impôts et taxes recouvrables sur des adhérents et autres",
    source: "map",
  },
  { number: "4426", label: "Droits de douane", source: "map" },
  { number: "4428", label: "Autres impôts et taxes", source: "map" },
  { number: "443", label: "État, T.V.A. Facturée", source: "map" },
  { number: "444", label: "Etat, T.V.A. due ou crédit de T.V.A.", source: "map" },
  { number: "445", label: "État, T.V.A. Récupérable", source: "map" },
  { number: "446", label: "Etat, autres taxes sur le chiffre d’affaires", source: "map" },
  { number: "447", label: "État, impôts retenus à la source", source: "map" },
  { number: "4471", label: "Impôt général sur le revenu", source: "map" },
  { number: "4472", label: "Impôts sur salaires", source: "map" },
  { number: "4473", label: "Contribution nationale", source: "map" },
  { number: "4474", label: "Contribution nationale de solidarité", source: "map" },
  { number: "4478", label: "Autres impôts et contributions", source: "map" },
  { number: "448", label: "État, charges à payer et produits à recevoir", source: "map" },
  { number: "4486", label: "Charges à payer", source: "map" },
  { number: "4487", label: "Produits à recevoir", source: "map" },
  { number: "449", label: "État, créances et dettes diverses", source: "map" },
  { number: "4491", label: "Etat, Subvention à recevoir", source: "map" },
  { number: "45", label: "FONDATEURS, APPORTEURS ET COMPTES COURANTS", source: "map" },
  { number: "451", label: "Associations et assimilées", source: "map" },
  { number: "4511", label: "Apporteurs en nature", source: "map" },
  { number: "4512", label: "Apporteurs en numéraire", source: "map" },
  { number: "4515", label: "Adhérents, dirigeants, comptes courants", source: "map" },
  { number: "452", label: "Fondations et assimilées", source: "map" },
  { number: "4521", label: "Apporteurs en nature", source: "map" },
  { number: "4522", label: "Apporteurs en numéraire", source: "map" },
  { number: "453", label: "Ordres professionnels", source: "map" },
  { number: "4531", label: "Apporteurs en nature", source: "map" },
  { number: "4532", label: "Apporteurs en numéraire", source: "map" },
  { number: "4535", label: "Membres, dirigeants, comptes courants", source: "map" },
  { number: "454", label: "Organisations politiques", source: "map" },
  { number: "4541", label: "Apporteurs en nature", source: "map" },
  { number: "4542", label: "Apporteurs en numéraire", source: "map" },
  { number: "4545", label: "Adhérents, dirigeants, comptes courants", source: "map" },
  { number: "455", label: "Organisations syndicales", source: "map" },
  { number: "4551", label: "Apporteurs en nature", source: "map" },
  { number: "4552", label: "Apporteurs en numéraire", source: "map" },
  { number: "4555", label: "Adhérents, dirigeants, comptes courants", source: "map" },
  { number: "456", label: "Organisations religieuses, apporteurs", source: "map" },
  { number: "4561", label: "Congrégations religieuses et assimilées", source: "map" },
  { number: "4562", label: "Waqf et assimilés", source: "map" },
  { number: "457", label: "Mécènes, bénévoles et assimilés", source: "map" },
  { number: "4571", label: "Mécènes et assimilés", source: "map" },
  { number: "4572", label: "Bénévoles et assimilés", source: "map" },
  { number: "458", label: "Autres fondateurs et apporteurs", source: "map" },
  { number: "46", label: "BAILLEURS, FONDS D'ADMINISTRATION", source: "map" },
  {
    number: "462",
    label: "Bailleurs - projet de développement, Fonds d'administration",
    source: "map",
  },
  { number: "463", label: "Etat - projet de développement, Fonds d'administration", source: "map" },
  {
    number: "464",
    label:
      "Autres tiers ou organismes de financement assimilés - projet de développement, Fonds d’administration",
    source: "map",
  },
  { number: "469", label: "Fonds d’administration à recevoir", source: "map" },
  { number: "4692", label: "Bailleurs -Fonds d'administration à recevoir", source: "map" },
  { number: "4693", label: "Etat -Fonds d'administration à recevoir", source: "map" },
  {
    number: "4694",
    label: "Autres tiers ou organismes de financement assimilés-Fonds d'administration à recevoir",
    source: "map",
  },
  { number: "47", label: "DÉBITEURS ET CRÉDITEURS DIVERS", source: "map" },
  { number: "471", label: "Débiteurs et créditeurs divers", source: "map" },
  { number: "4711", label: "Débiteurs divers", source: "map" },
  { number: "4712", label: "Créditeurs divers", source: "map" },
  { number: "4713", label: "Créditeurs, dons en nature courants non consommés", source: "map" },
  { number: "4717", label: "Débiteurs divers - retenues de garantie", source: "map" },
  { number: "4719", label: "Bons de souscription d'actions et d'obligations", source: "map" },
  { number: "472", label: "Créances et dettes sur titres de placement", source: "map" },
  { number: "4721", label: "Créances sur cessions de titres de placement", source: "map" },
  {
    number: "4726",
    label: "Versements restant à effectuer sur titres de placement non libérés",
    source: "map",
  },
  {
    number: "473",
    label: "Organismes nationaux et internationaux — subventions à recevoir",
    source: "map",
  },
  { number: "4731", label: "Subventions d'investissement à recevoir", source: "map" },
  { number: "4732", label: "Subventions d'exploitation à recevoir", source: "map" },
  { number: "4733", label: "Subventions d'équilibre à recevoir", source: "map" },
  { number: "4738", label: "Autres subventions à recevoir", source: "map" },
  { number: "4739", label: "Subventions à reverser", source: "map" },
  {
    number: "474",
    label: "Compte de répartition périodique des charges et des produits",
    source: "map",
  },
  { number: "4746", label: "Compte de répartition périodique des charges", source: "map" },
  { number: "4747", label: "Compte de répartition périodique des produits", source: "map" },
  { number: "475", label: "Générosités financières à recevoir", source: "map" },
  { number: "476", label: "Charges constatées d’avance", source: "map" },
  { number: "477", label: "Produits constatés d’avance", source: "map" },
  { number: "478", label: "Écarts de conversion - actif", source: "map" },
  { number: "4781", label: "Diminution des créances d'exploitation et HAO", source: "map" },
  { number: "47811", label: "Diminution des créances d'exploitation", source: "map" },
  { number: "47818", label: "Diminution des créances HAO", source: "map" },
  { number: "4782", label: "Diminution des créances financières", source: "map" },
  { number: "4783", label: "Augmentation des dettes d'exploitation et HAO", source: "map" },
  { number: "47831", label: "Augmentation des dettes d'exploitation", source: "map" },
  { number: "47838", label: "Augmentation des dettes HAO", source: "map" },
  { number: "4784", label: "Augmentation des dettes financières", source: "map" },
  {
    number: "4786",
    label: "Différences d'évaluation sur instruments de trésorerie",
    source: "map",
  },
  { number: "4788", label: "Différences compensées par couverture de change", source: "map" },
  { number: "479", label: "Écarts de conversion — passif", source: "map" },
  { number: "4791", label: "Augmentation des créances d'exploitation et HAO", source: "map" },
  { number: "47911", label: "Augmentation des créances d'exploitation", source: "map" },
  { number: "47918", label: "Augmentation des créances HAO", source: "map" },
  { number: "4792", label: "Augmentation des créances financières", source: "map" },
  { number: "4793", label: "Diminution des dettes d'exploitation et HAO", source: "map" },
  { number: "47931", label: "Diminution des dettes d'exploitation", source: "map" },
  { number: "47938", label: "Diminution des dettes HAO", source: "map" },
  { number: "4794", label: "Diminution des dettes financières", source: "map" },
  {
    number: "4797",
    label: "Différences d'évaluation sur instruments de trésorerie",
    source: "map",
  },
  { number: "4798", label: "Différences compensées par couverture de change", source: "map" },
  { number: "48", label: "CRÉANCES ET DETTES HORS ACTIVITÉS ORDINAIRES (H.A.O.)", source: "map" },
  { number: "481", label: "Fournisseurs d’investissements", source: "map" },
  { number: "4811", label: "Fournisseurs, immobilisations incorporelles", source: "map" },
  { number: "4812", label: "Fournisseurs, immobilisations corporelles", source: "map" },
  {
    number: "4813",
    label:
      "Versements restant à effectuer sur titres de participation et titres immobilisés non libérés",
    source: "map",
  },
  { number: "4816", label: "Fournisseurs, réserve de propriété - immobilisations", source: "map" },
  {
    number: "48161",
    label: "Fournisseurs, réserve de propriété — immobilisations incorporelles",
    source: "map",
  },
  {
    number: "48162",
    label: "Fournisseurs, réserve de propriété — immobilisations corporelles",
    source: "map",
  },
  { number: "4817", label: "Fournisseurs, retenues de garantie- immobilisations", source: "map" },
  {
    number: "48171",
    label: "Fournisseurs, retenues de garantie — immobilisations incorporelles",
    source: "map",
  },
  {
    number: "48172",
    label: "Fournisseurs, retenues de garantie — immobilisations corporelles",
    source: "map",
  },
  {
    number: "4818",
    label: "Fournisseurs, factures non parvenues - immobilisations",
    source: "map",
  },
  {
    number: "48181",
    label: "Fournisseurs, factures non parvenues — immobilisations incorporelles",
    source: "map",
  },
  {
    number: "48182",
    label: "Fournisseurs, factures non parvenues — immobilisations corporelles",
    source: "map",
  },
  { number: "484", label: "Autres dettes hors activités ordinaires (H.A.O.)", source: "map" },
  { number: "485", label: "Créances sur cessions d’immobilisations", source: "map" },
  { number: "4851", label: "Créances, en compte, immobilisations incorporelles", source: "map" },
  { number: "4852", label: "Créances, en compte, immobilisations corporelles", source: "map" },
  { number: "4856", label: "Créances, immobilisations financières", source: "map" },
  {
    number: "4857",
    label: "Créances, Retenues de garantie sur cession immobilisations",
    source: "map",
  },
  {
    number: "4858",
    label: "Créances sur cession d’immobilisations, factures à établir",
    source: "map",
  },
  { number: "486", label: "Dettes et créances des legs et dons d’immobilisations", source: "map" },
  { number: "4861", label: "Dettes des dons et legs d’immobilisations", source: "map" },
  { number: "4865", label: "Créances reçues sur dons et legs d’immobilisations", source: "map" },
  { number: "488", label: "Autres créances hors activités ordinaires (H.A.O.)", source: "map" },
  { number: "4881", label: "Créditeurs, dons en nature HAO non consommés", source: "map" },
  { number: "49", label: "DÉPRÉCIATIONS ET PROVISIONS POUR RISQUES A COURT TERME", source: "map" },
  { number: "490", label: "Dépréciations des comptes fournisseurs", source: "map" },
  { number: "491", label: "Dépréciations des comptes adhérents et clients-usagers", source: "map" },
  { number: "4911", label: "Dépréciations des créances litigieuses", source: "map" },
  { number: "4912", label: "Dépréciations des créances douteuses", source: "map" },
  { number: "492", label: "Dépréciations des comptes personnel", source: "map" },
  { number: "493", label: "Dépréciations des comptes organismes sociaux", source: "map" },
  {
    number: "494",
    label: "Dépréciations des comptes État et Collectivités publiques",
    source: "map",
  },
  { number: "497", label: "Dépréciations des comptes débiteurs divers", source: "map" },
  { number: "498", label: "Dépréciations des comptes de créances H.A.O.", source: "map" },
  {
    number: "4985",
    label: "Dépréciations des créances sur cessions d’immobilisations",
    source: "map",
  },
  { number: "4988", label: "Dépréciations des autres créances H.A.O.", source: "map" },
  { number: "499", label: "Provisions pour risques et charges à court terme", source: "map" },
  { number: "4991", label: "Provisions pour risques sur opérations d'exploitation", source: "map" },
  { number: "4998", label: "Provisions pour risques sur opérations H.A.O.", source: "map" },
  { number: "50", label: "TITRES DE PLACEMENT", source: "map" },
  { number: "501", label: "Titres du trésor et bons de caisse à court terme", source: "map" },
  { number: "5011", label: "Titres du Trésor à court terme", source: "map" },
  { number: "5012", label: "Titres d’organismes financiers", source: "map" },
  { number: "5013", label: "Bons de caisse à court terme", source: "map" },
  {
    number: "5016",
    label: "Frais d'acquisition des titres de trésor et bons de caisse",
    source: "map",
  },
  { number: "502", label: "Actions", source: "map" },
  { number: "5022", label: "Actions cotées", source: "map" },
  { number: "5023", label: "Actions non cotées", source: "map" },
  { number: "5025", label: "Autres actions", source: "map" },
  { number: "5026", label: "Frais d'acquisition des actions", source: "map" },
  { number: "503", label: "Obligations", source: "map" },
  { number: "5032", label: "Obligations cotées", source: "map" },
  { number: "5033", label: "Obligations non cotées", source: "map" },
  { number: "5035", label: "Autres obligations", source: "map" },
  { number: "5036", label: "Frais d'acquisition des obligations", source: "map" },
  { number: "504", label: "Bons de souscription", source: "map" },
  { number: "5042", label: "Bons de souscription d'actions", source: "map" },
  { number: "5043", label: "Bons de souscription d’ obligations", source: "map" },
  { number: "505", label: "Titres négociables hors Région", source: "map" },
  { number: "506", label: "Intérêts courus", source: "map" },
  { number: "5061", label: "Titres du Trésor et bons de caisse à court terme", source: "map" },
  { number: "5062", label: "Actions", source: "map" },
  { number: "5063", label: "Obligations", source: "map" },
  { number: "508", label: "Autres titres de placement et créances assimilées", source: "map" },
  { number: "51", label: "VALEURS À ENCAISSER", source: "map" },
  { number: "513", label: "Chèques à encaisser", source: "map" },
  { number: "514", label: "Chèques à l’encaissement", source: "map" },
  { number: "515", label: "Cartes de crédit à encaisser", source: "map" },
  { number: "518", label: "Autres valeurs à l’encaissement", source: "map" },
  { number: "5185", label: "Chèques de voyage", source: "map" },
  { number: "5186", label: "Coupons échus", source: "map" },
  { number: "5187", label: "Intérêts échus des obligations", source: "map" },
  { number: "52", label: "BANQUES", source: "map" },
  { number: "521", label: "Banques locales", source: "map" },
  { number: "5211", label: "Banques en monnaie nationale", source: "map" },
  { number: "5215", label: "Banques en devises", source: "map" },
  { number: "522", label: "Banques autres États Région", source: "map" },
  { number: "523", label: "Banques autres États zone monétaire", source: "map" },
  { number: "524", label: "Banques hors zone monétaire", source: "map" },
  { number: "525", label: "Banques dépôt à terme et opérations assimilées", source: "map" },
  { number: "526", label: "Banques, intérêts courus", source: "map" },
  { number: "5261", label: "Banque, intérêts courus charges à payer", source: "map" },
  { number: "5267", label: "Banque, intérêts courus produits à recevoir", source: "map" },
  { number: "53", label: "ÉTABLISSEMENTS FINANCIERS ET ASSIMILES", source: "map" },
  { number: "531", label: "Banques postales", source: "map" },
  { number: "532", label: "Trésor", source: "map" },
  { number: "533", label: "Sociétés de gestion et d’intermédiation (S.G.L)", source: "map" },
  { number: "536", label: "Etablissements financiers, intéréts courus", source: "map" },
  {
    number: "5361",
    label: "Établissements financiers, intérêts courus charges à payer",
    source: "map",
  },
  {
    number: "5367",
    label: "Établissements financiers, intérêts courus produits à recevoir",
    source: "map",
  },
  { number: "538", label: "Autres organismes financiers", source: "map" },
  { number: "55", label: "INSTRUMENTS DE MONNAIE ELECTRONIQUE", source: "map" },
  { number: "551", label: "Monnaie électronique - carte carburant", source: "map" },
  { number: "552", label: "Monnaie électronique - téléphone portable", source: "map" },
  { number: "553", label: "Monnaie électronique - carte péage", source: "map" },
  { number: "554", label: "Porte-monnaie électronique", source: "map" },
  { number: "558", label: "Autres instruments de monnaie électronique", source: "map" },
  { number: "56", label: "BANQUES, CRÉDITS DE TRÉSORERIE ET D'ESCOMPTE", source: "map" },
  { number: "561", label: "Crédits de trésorerie", source: "map" },
  { number: "565", label: "Escompte de crédits ordinaires", source: "map" },
  { number: "566", label: "Banques, crédits de trésorerie, intérêts courus", source: "map" },
  { number: "57", label: "CAISSE", source: "map" },
  { number: "571", label: "Caisse en monnaie nationale", source: "map" },
  { number: "572", label: "Caisse en devises", source: "map" },
  { number: "58", label: "VIREMENTS INTERNES", source: "map" },
  { number: "585", label: "Virements de fonds", source: "map" },
  { number: "588", label: "Autres virements internes", source: "map" },
  { number: "59", label: "DEPRECIATIONS ET PROVISIONS POUR RISQUES A COURT TERME", source: "map" },
  { number: "590", label: "Dépréciations des titres de placement", source: "map" },
  { number: "591", label: "Dépréciations des titres et valeurs à encaisser", source: "map" },
  { number: "592", label: "Dépréciations des comptes banques", source: "map" },
  {
    number: "593",
    label: "Dépréciations des comptes établissements financiers et assimilés",
    source: "map",
  },
  {
    number: "595",
    label: "Dépréciations des comptes d’instruments de monnaie électronique",
    source: "map",
  },
  {
    number: "599",
    label: "Provisions pour risque et charges à court terme à caractère financier",
    source: "map",
  },
  { number: "60", label: "ACHATS ET VARIATIONS DE STOCKS", source: "map" },
  { number: "601", label: "Achats de biens et services liés à l’activité", source: "map" },
  {
    number: "6011",
    label: "Achats de biens et services liés à l’activité dans l'Etat partie",
    source: "map",
  },
  {
    number: "6012",
    label: "Achats de biens et services liés à l’activité dans la Région",
    source: "map",
  },
  {
    number: "6013",
    label: "Achats de biens et services liés à l’activité hors Région",
    source: "map",
  },
  {
    number: "6015",
    label: "Frais sur achats de biens et services liés à l’activité",
    source: "map",
  },
  { number: "6019", label: "Rabais, Remises et Ristournes obtenus (non ventilés)", source: "map" },
  {
    number: "602",
    label: "Achats de marchandises, de matières premières et fournitures liées",
    source: "map",
  },
  {
    number: "6021",
    label: "Achats de marchandises et matières premières dans l’État partie",
    source: "map",
  },
  {
    number: "6022",
    label: "Achats de marchandises et matières premières dans la Région",
    source: "map",
  },
  {
    number: "6023",
    label: "Achats de marchandises et matières premières hors Région",
    source: "map",
  },
  { number: "6025", label: "Frais sur achats de marchandises et matières", source: "map" },
  { number: "6029", label: "Rabais, Remises et Ristournes obtenus (non ventilés)", source: "map" },
  {
    number: "603",
    label: "Variations des stocks de biens achetés et reçus en dons en nature à distribuer",
    source: "map",
  },
  {
    number: "6031",
    label: "Variations des stocks de biens et services liés à l’activité",
    source: "map",
  },
  { number: "6032", label: "Variations des stocks de marchandises", source: "map" },
  {
    number: "6033",
    label: "Variations des stocks de matières premières et fournitures liées",
    source: "map",
  },
  { number: "6034", label: "Variations des stocks d’autres approvisionnements", source: "map" },
  { number: "6035", label: "Variations de stocks de dons en nature à distribuer", source: "map" },
  { number: "604", label: "Achats stockés de matières et fournitures consommables", source: "map" },
  { number: "6041", label: "Matières consommables", source: "map" },
  { number: "6042", label: "Matières combustibles", source: "map" },
  { number: "6043", label: "Produits d'entretien", source: "map" },
  {
    number: "6045",
    label: "Frais sur achats de matières et fournitures consommables",
    source: "map",
  },
  { number: "6046", label: "Fournitures de magasin", source: "map" },
  { number: "6047", label: "Fournitures de bureau", source: "map" },
  { number: "6049", label: "Rabais, Remises et Ristournes obtenus (non ventilés)", source: "map" },
  { number: "605", label: "Autres achats", source: "map" },
  { number: "6051", label: "Fournitures non stockables Eau", source: "map" },
  { number: "6052", label: "Fournitures non stockables - Électricité", source: "map" },
  { number: "6053", label: "Fournitures non stockables — Autres énergies", source: "map" },
  { number: "6054", label: "Fournitures d'entretien non stockables", source: "map" },
  { number: "6055", label: "Fournitures de bureau non stockables", source: "map" },
  { number: "6056", label: "Achats de petit matériel et outillage", source: "map" },
  { number: "6057", label: "Achats d’études et prestations de services", source: "map" },
  { number: "6058", label: "Achats de travaux, matériels et équipements", source: "map" },
  { number: "6059", label: "Rabais, Remises et Ristournes obtenus (non ventilés)", source: "map" },
  { number: "606", label: "Achats autres activités", source: "map" },
  { number: "6061", label: "Billetteries", source: "map" },
  { number: "6062", label: "Tombola et autres jeux", source: "map" },
  { number: "6063", label: "Bons d’achats", source: "map" },
  { number: "6064", label: "Voyages et sorties", source: "map" },
  { number: "6068", label: "Autres activités", source: "map" },
  { number: "608", label: "Achats d'emballages", source: "map" },
  { number: "6081", label: "Emballages perdus", source: "map" },
  { number: "6082", label: "Emballages récupérables non identifiables", source: "map" },
  { number: "6083", label: "Emballages à usage mixte", source: "map" },
  { number: "6085", label: "Frais sur achats d’emballages", source: "map" },
  { number: "6089", label: "Rabais, Remises et Ristournes obtenus (non ventilés)", source: "map" },
  { number: "61", label: "TRANSPORTS", source: "map" },
  { number: "612", label: "Transports sur ventes", source: "map" },
  { number: "613", label: "Transports pour le compte de tiers", source: "map" },
  { number: "614", label: "Transports du personnel", source: "map" },
  { number: "616", label: "Transports de plis", source: "map" },
  { number: "618", label: "Autres frais de transport", source: "map" },
  { number: "6181", label: "Voyages et déplacements", source: "map" },
  { number: "6183", label: "Transports administratifs", source: "map" },
  { number: "619", label: "Rabais, Remises et Ristournes Obtenus (non ventilés)", source: "map" },
  { number: "62", label: "SERVICES EXTÉRIEURS", source: "map" },
  { number: "621", label: "Sous-traitance générale", source: "map" },
  { number: "622", label: "Locations, charges locatives", source: "map" },
  { number: "6221", label: "Locations de terrains", source: "map" },
  { number: "6222", label: "Locations de bâtiments", source: "map" },
  { number: "6223", label: "Locations de matériels et outillages", source: "map" },
  { number: "6224", label: "Malis sur emballages", source: "map" },
  { number: "6225", label: "Locations d'emballages", source: "map" },
  { number: "6226", label: "Fermages et loyers du foncier", source: "map" },
  { number: "6228", label: "Locations et charges locatives diverses", source: "map" },
  { number: "623", label: "Redevances de location-acquisition", source: "map" },
  { number: "6232", label: "Crédit-bail immobilier", source: "map" },
  { number: "6233", label: "Crédit-bail mobilier", source: "map" },
  { number: "6234", label: "Location-vente", source: "map" },
  { number: "6238", label: "Autres contrats de location-acquisition", source: "map" },
  { number: "624", label: "Entretien, réparation, remise en état et maintenance", source: "map" },
  { number: "6241", label: "Entretien et réparation des biens immobiliers", source: "map" },
  { number: "6242", label: "Entretien et réparation des biens mobiliers", source: "map" },
  { number: "6243", label: "Maintenance", source: "map" },
  { number: "6244", label: "Charges de démantèlement et remise en état", source: "map" },
  { number: "6248", label: "Autres entretiens et réparation", source: "map" },
  { number: "625", label: "Primes d’assurance", source: "map" },
  { number: "6251", label: "Assurances multirisques", source: "map" },
  { number: "6252", label: "Assurances matériel de transport", source: "map" },
  { number: "6253", label: "Assurances risques d'exploitation", source: "map" },
  { number: "6258", label: "Autres primes d'assurances", source: "map" },
  { number: "626", label: "Études, recherches et documentation", source: "map" },
  { number: "6261", label: "Études et recherches", source: "map" },
  { number: "6265", label: "Documentation générale", source: "map" },
  { number: "6266", label: "Documentation technique", source: "map" },
  { number: "627", label: "Publicité, publications, relations publiques", source: "map" },
  { number: "6271", label: "Annonces, insertions", source: "map" },
  { number: "6272", label: "Catalogues, imprimés publicitaires", source: "map" },
  { number: "6273", label: "Congrès, universités et assimilés", source: "map" },
  { number: "6274", label: "Manifestations", source: "map" },
  { number: "6275", label: "Publications", source: "map" },
  { number: "6277", label: "Frais de colloques, séminaires, conférences", source: "map" },
  { number: "6278", label: "Autres charges de publicité et relations publiques", source: "map" },
  { number: "628", label: "Frais de télécommunications", source: "map" },
  { number: "6281", label: "Frais de téléphone", source: "map" },
  { number: "6283", label: "Frais de télécopie", source: "map" },
  { number: "6284", label: "Frais d'internet", source: "map" },
  { number: "6288", label: "Autres frais de télécommunications", source: "map" },
  { number: "63", label: "AUTRES SERVICES EXTÉRIEURS", source: "map" },
  { number: "631", label: "Frais bancaires", source: "map" },
  { number: "6311", label: "Frais sur titres (vente, garde)", source: "map" },
  { number: "6312", label: "Frais sur effets", source: "map" },
  { number: "6313", label: "Location de coffres", source: "map" },
  { number: "6315", label: "Commissions sur cartes de crédit", source: "map" },
  { number: "6316", label: "Frais d'émission d'emprunts", source: "map" },
  { number: "6317", label: "Frais sur instruments de monnaie électronique", source: "map" },
  { number: "6318", label: "Autres frais bancaires", source: "map" },
  { number: "632", label: "Rémunérations d’intermédiaires et de conseils", source: "map" },
  { number: "6322", label: "Commissions", source: "map" },
  { number: "6324", label: "Honoraires des professions règlementées", source: "map" },
  { number: "6325", label: "Frais d’actes et de contentieux", source: "map" },
  { number: "6327", label: "Rémunérations des autres prestataires de services", source: "map" },
  { number: "6328", label: "Divers frais", source: "map" },
  { number: "633", label: "Frais de formation", source: "map" },
  {
    number: "634",
    label:
      "Redevances pour brevets, licences, logiciels, sites internet, concessions et droits et valeurs similaires",
    source: "map",
  },
  { number: "6342", label: "Redevances pour brevets, licences", source: "map" },
  { number: "6343", label: "Redevances pour logiciels", source: "map" },
  { number: "6345", label: "Redevances pour sites internet", source: "map" },
  {
    number: "6346",
    label: "Redevances pour concessions, droits et valeurs similaires",
    source: "map",
  },
  { number: "6348", label: "Autres redevances", source: "map" },
  { number: "635", label: "Cotisations", source: "map" },
  { number: "6351", label: "Cotisations", source: "map" },
  { number: "6358", label: "Concours divers", source: "map" },
  { number: "636", label: "Frais de recherche de fonds", source: "map" },
  { number: "637", label: "Rémunérations de personnel extérieur à l’entité", source: "map" },
  { number: "6371", label: "Personnel intérimaire", source: "map" },
  { number: "6372", label: "Personnel détaché ou prêté à l'entité", source: "map" },
  { number: "638", label: "Autres charges externes", source: "map" },
  { number: "6381", label: "Frais de recrutement du personnel", source: "map" },
  { number: "6382", label: "Frais de déménagement", source: "map" },
  { number: "6383", label: "Réceptions", source: "map" },
  { number: "6384", label: "Missions", source: "map" },
  { number: "6385", label: "Charges de copropriété", source: "map" },
  { number: "6388", label: "Charges externes diverses", source: "map" },
  { number: "64", label: "IMPÔTS ET TAXES", source: "map" },
  { number: "641", label: "Impôts et taxes directs", source: "map" },
  { number: "6411", label: "Impôts fonciers et taxes annexes", source: "map" },
  { number: "6412", label: "Licences et taxes annexes", source: "map" },
  { number: "6413", label: "Taxes sur appointements et salaires", source: "map" },
  { number: "6414", label: "Taxes d'apprentissage", source: "map" },
  { number: "6415", label: "Formation professionnelle continue", source: "map" },
  { number: "6416", label: "Patente ou contribution économique locale", source: "map" },
  { number: "6418", label: "Autres impôts et taxes directs", source: "map" },
  { number: "645", label: "Impôts et taxes indirects", source: "map" },
  { number: "646", label: "Droits d’enregistrement", source: "map" },
  { number: "6461", label: "Droits de mutation", source: "map" },
  { number: "6462", label: "Droits de timbre", source: "map" },
  { number: "6464", label: "Vignettes", source: "map" },
  { number: "6468", label: "Autres droits d'enregistrement", source: "map" },
  { number: "647", label: "Pénalités, amendes fiscales", source: "map" },
  { number: "6471", label: "Pénalités d’assiette, impôts directs", source: "map" },
  { number: "6472", label: "Pénalités d’assiette, impôts indirects", source: "map" },
  { number: "6473", label: "Pénalités de recouvrement, impôts directs", source: "map" },
  { number: "6474", label: "Pénalités de recouvrement, impôts indirects", source: "map" },
  { number: "6478", label: "Autres pénalités et amendes fiscales", source: "map" },
  { number: "648", label: "Autres impôts et taxes", source: "map" },
  { number: "649", label: "Dégrèvements et annulations des impôts et taxes", source: "map" },
  { number: "65", label: "AUTRES CHARGES", source: "map" },
  {
    number: "651",
    label: "Pertes sur créances adhérents, clients et autres débiteurs",
    source: "map",
  },
  { number: "6511", label: "Clients-usagers", source: "map" },
  { number: "6512", label: "Adhérents", source: "map" },
  { number: "6515", label: "Autres débiteurs", source: "map" },
  { number: "652", label: "Subventions accordées par l’entité", source: "map" },
  { number: "654", label: "Dons en nature courants à distribuer", source: "map" },
  { number: "6541", label: "Dons en nature courants à distribuer non affectés", source: "map" },
  { number: "6545", label: "Dons en nature courants à distribuer affectés", source: "map" },
  { number: "657", label: "Pénalités et amendes pénales", source: "map" },
  { number: "658", label: "Charges diverses", source: "map" },
  {
    number: "659",
    label: "Charges pour dépréciations et provisions pour risques à court terme d’exploitation",
    source: "map",
  },
  { number: "6591", label: "Provisions sur risques à court terme", source: "map" },
  { number: "6593", label: "Charges pour dépréciations sur stocks", source: "map" },
  { number: "6594", label: "Charges pour dépréciations sur créances", source: "map" },
  {
    number: "6598",
    label: "Autres charges pour dépréciations et provisions pour risques à court terme",
    source: "map",
  },
  { number: "66", label: "CHARGES DE PERSONNEL", source: "map" },
  { number: "661", label: "Rémunérations directes versées au personnel national", source: "map" },
  { number: "6611", label: "Appointements salaires et commissions", source: "map" },
  { number: "6612", label: "Primes et gratifications", source: "map" },
  { number: "6613", label: "Congés payés", source: "map" },
  { number: "6614", label: "Indemnités de préavis et de licenciement", source: "map" },
  { number: "6615", label: "Indemnités de maladie versées aux travailleurs", source: "map" },
  { number: "6616", label: "Supplément familial", source: "map" },
  { number: "6617", label: "Avantages en nature", source: "map" },
  { number: "6618", label: "Autres rémunérations directes", source: "map" },
  {
    number: "662",
    label: "Rémunérations directes versées au personnel non national",
    source: "map",
  },
  { number: "6621", label: "Appointements salaires et commissions", source: "map" },
  { number: "6622", label: "Primes et gratifications", source: "map" },
  { number: "6623", label: "Congés payés", source: "map" },
  { number: "6624", label: "Indemnités de préavis et de licenciement", source: "map" },
  { number: "6625", label: "Indemnités de maladie versées aux travailleurs", source: "map" },
  { number: "6626", label: "Supplément familial", source: "map" },
  { number: "6627", label: "Avantages en nature", source: "map" },
  { number: "6628", label: "Autres rémunérations directes", source: "map" },
  { number: "663", label: "Indemnités forfaitaires versées au personnel", source: "map" },
  { number: "6631", label: "Indemnités de logement", source: "map" },
  { number: "6632", label: "Indemnités de représentation", source: "map" },
  { number: "6633", label: "Indemnités d’expatriation", source: "map" },
  { number: "6634", label: "Indemnités de transport", source: "map" },
  { number: "6638", label: "Autres indemnités et avantages divers", source: "map" },
  { number: "664", label: "Charges sociales", source: "map" },
  {
    number: "6641",
    label: "Charges sociales sur rémunération du personnel national",
    source: "map",
  },
  {
    number: "6642",
    label: "Charges sociales sur rémunération du personnel non national",
    source: "map",
  },
  { number: "665", label: "Habillement et équipement du personnel", source: "map" },
  { number: "667", label: "Rémunération transférée de personnel extérieur", source: "map" },
  { number: "6671", label: "Personnel intérimaire", source: "map" },
  { number: "6672", label: "Personnel détaché ou prêté à l'entité", source: "map" },
  { number: "668", label: "Autres charges sociales", source: "map" },
  { number: "6681", label: "Versements aux syndicats et assimilés", source: "map" },
  { number: "6682", label: "Versements aux comités d'hygiène et de sécurité", source: "map" },
  {
    number: "6683",
    label: "Versements et contributions aux autres œuvres sociales",
    source: "map",
  },
  { number: "6684", label: "Médecine du travail et pharmacie", source: "map" },
  { number: "6685", label: "Assurances et organismes de santé", source: "map" },
  { number: "6686", label: "Assurances retraite et fonds de pensions", source: "map" },
  { number: "6687", label: "Majorations et pénalités sociales", source: "map" },
  { number: "6688", label: "Charges sociales diverses", source: "map" },
  { number: "669", label: "Dégrèvements et annulations des charges sociales", source: "map" },
  { number: "67", label: "FRAIS FINANCIERS ET CHARGES ASSIMILEES", source: "map" },
  { number: "671", label: "Intérêts des emprunts", source: "map" },
  { number: "6711", label: "Emprunts obligataires", source: "map" },
  { number: "6712", label: "Emprunts auprès des établissements de crédit", source: "map" },
  { number: "6713", label: "Primes de remboursement des obligations", source: "map" },
  { number: "672", label: "Intérêts dans loyers de location-acquisition", source: "map" },
  {
    number: "6721",
    label: "Intérêts dans loyers de location-acquisition/crédit-bail immobilier",
    source: "map",
  },
  {
    number: "6722",
    label: "Intérêts dans loyers de location-acquisition/crédit-bail mobilier",
    source: "map",
  },
  {
    number: "6723",
    label: "Intérêts dans loyers de location-acquisition/location-vente",
    source: "map",
  },
  { number: "6724", label: "Intérêts dans loyers des autres locations-acquisition", source: "map" },
  { number: "673", label: "Escomptes accordés", source: "map" },
  { number: "674", label: "Autres intérêts", source: "map" },
  { number: "6741", label: "Avances reçues et dépôts créditeurs", source: "map" },
  { number: "6742", label: "Comptes courants bloqués", source: "map" },
  { number: "6744", label: "Intérêts sur dettes commerciales", source: "map" },
  {
    number: "6745",
    label: "Intérêts bancaires et sur opérations de financement (escompte...)",
    source: "map",
  },
  { number: "6748", label: "Intérêts sur dettes diverses", source: "map" },
  { number: "676", label: "Pertes de change financières", source: "map" },
  { number: "677", label: "Pertes sur titres de placement", source: "map" },
  { number: "6771", label: "Pertes sur cessions de titres de placement", source: "map" },
  { number: "678", label: "Pertes et charges sur risques financiers", source: "map" },
  { number: "6781", label: "sur rentes viagères", source: "map" },
  { number: "6782", label: "sur opérations financières", source: "map" },
  {
    number: "679",
    label: "Charges pour dépréciations et provisions pour risques à court terme financières",
    source: "map",
  },
  { number: "6791", label: "sur risques financiers", source: "map" },
  { number: "6795", label: "sur titres de placement", source: "map" },
  {
    number: "6798",
    label: "Autres charges pour dépréciations et provisions pour risques à court terme financières",
    source: "map",
  },
  { number: "68", label: "DOTATIONS AUX AMORTISSEMENTS", source: "map" },
  { number: "680", label: "Dotations aux amortissements d’usufruit temporaire", source: "map" },
  { number: "681", label: "Dotations aux amortissements d’exploitation", source: "map" },
  {
    number: "6812",
    label: "Dotations aux amortissements des immobilisations incorporelles",
    source: "map",
  },
  {
    number: "6813",
    label: "Dotations aux amortissements des immobilisations corporelles",
    source: "map",
  },
  { number: "69", label: "DOTATIONS AUX PROVISIONS ET AUX DÉPRÉCIATIONS", source: "map" },
  {
    number: "691",
    label: "Dotations aux provisions et aux dépréciations d’exploitation",
    source: "map",
  },
  { number: "6911", label: "Dotations aux provisions pour risques et charges", source: "map" },
  {
    number: "6913",
    label: "Dotations aux dépréciations des immobilisations incorporelles",
    source: "map",
  },
  {
    number: "6914",
    label: "Dotations aux dépréciations des immobilisations corporelles",
    source: "map",
  },
  {
    number: "695",
    label:
      "Dotations aux dépréciations d’immobilisations destinées à la vente provenant des dons et legs non encore reçus et d’usufruit temporaire",
    source: "map",
  },
  { number: "6951", label: "Dotations aux dépréciations d’usufruit temporaire", source: "map" },
  {
    number: "6952",
    label:
      "Dotations aux dépréciations d’immobilisations destinées à la vente provenant des dons et legs non encore reçus",
    source: "map",
  },
  {
    number: "697",
    label: "Dotations aux provisions et aux dépréciations financières",
    source: "map",
  },
  { number: "6971", label: "Dotations aux provisions pour risques et charges", source: "map" },
  {
    number: "6972",
    label: "Dotations aux dépréciations des immobilisations financières",
    source: "map",
  },
  { number: "70", label: "REVENUS", source: "map" },
  { number: "701", label: "Cotisations des adhérents", source: "map" },
  { number: "702", label: "Quote-part de fonds d’administration transférés", source: "map" },
  { number: "703", label: "Quote-part de dotation consomptible transférée", source: "map" },
  { number: "704", label: "Revenus liés à la générosité", source: "map" },
  { number: "7041", label: "Dons", source: "map" },
  { number: "7042", label: "Legs", source: "map" },
  { number: "7043", label: "Deniers du culte", source: "map" },
  { number: "7044", label: "Zakat, Dime, quête et assimilées", source: "map" },
  { number: "7045", label: "Célébrations", source: "map" },
  { number: "7046", label: "Mécénats", source: "map" },
  { number: "7047", label: "Parrainage", source: "map" },
  { number: "7048", label: "Autres revenus liés à la générosité", source: "map" },
  { number: "705", label: "Ventes marchandises, services et produits finis", source: "map" },
  { number: "7051", label: "Ventes marchandises", source: "map" },
  { number: "7052", label: "Services vendus", source: "map" },
  { number: "7053", label: "Ventes de produits finis", source: "map" },
  { number: "7054", label: "Ventes de produits intermédiaires", source: "map" },
  { number: "7055", label: "Ventes de produits résiduels", source: "map" },
  { number: "706", label: "Revenus des manifestations", source: "map" },
  { number: "707", label: "Produits accessoires", source: "map" },
  { number: "708", label: "Autres revenus", source: "map" },
  { number: "7081", label: "Ventes de dons en nature", source: "map" },
  { number: "7082", label: "Revenus d’usufruit", source: "map" },
  { number: "71", label: "SUBVENTIONS D'EXPLOITATION", source: "map" },
  {
    number: "711",
    label: "Subventions d'exploitation versées par l’État et les Collectivités publiques",
    source: "map",
  },
  {
    number: "713",
    label: "Subventions d’exploitation versées par les organismes nationaux et internationaux",
    source: "map",
  },
  { number: "718", label: "Autres subventions d’exploitation", source: "map" },
  { number: "72", label: "PRODUCTION IMMOBILISEE", source: "map" },
  { number: "721", label: "Production immobilisée, immobilisations incorporelles", source: "map" },
  { number: "722", label: "Production immobilisée, immobilisations corporelles", source: "map" },
  { number: "724", label: "Production auto-consommée", source: "map" },
  { number: "726", label: "Production immobilisée, immobilisations financières", source: "map" },
  { number: "73", label: "VARIATIONS DES STOCKS DE BIENS PRODUITS", source: "map" },
  {
    number: "735",
    label: "Variations des stocks de produits finis et services en cours",
    source: "map",
  },
  {
    number: "736",
    label: "Variations des stocks de produits finis, produits intermédiaires et résiduels.",
    source: "map",
  },
  { number: "75", label: "AUTRES PRODUITS", source: "map" },
  {
    number: "751",
    label: "Profits sur créances Adhérents, clients-usagers, et autres débiteurs",
    source: "map",
  },
  { number: "752", label: "Contribution du fondateur", source: "map" },
  { number: "754", label: "Dons en nature courants", source: "map" },
  { number: "7542", label: "Dons en nature courants reçus à distribuer", source: "map" },
  { number: "758", label: "Produits divers", source: "map" },
  { number: "7582", label: "Indemnités d'assurances reçues", source: "map" },
  { number: "7583", label: "Abandons de frais par les bénévoles", source: "map" },
  { number: "7588", label: "Autres produits divers", source: "map" },
  {
    number: "759",
    label:
      "Reprises de charges pour dépréciations et provisions pour risques à court terme d’exploitation",
    source: "map",
  },
  { number: "7591", label: "Reprises provisions sur risques à court terme", source: "map" },
  { number: "7593", label: "Reprises de charges pour dépréciations sur stocks", source: "map" },
  { number: "7594", label: "Reprises de charges pour dépréciations sur créances", source: "map" },
  {
    number: "7598",
    label:
      "Autres reprises de charges pour dépréciations et provisions pour risques à court terme d’exploitation",
    source: "map",
  },
  { number: "77", label: "REVENUS FINANCIERS ET PRODUITS ASSIMILES", source: "map" },
  { number: "771", label: "Intérêts de prêts et créances diverses", source: "map" },
  { number: "7712", label: "Intérêts de prêts", source: "map" },
  { number: "7713", label: "Intérêts sur créances diverses", source: "map" },
  { number: "772", label: "Revenus de participations et autres titres immobilisés", source: "map" },
  { number: "7721", label: "Revenus des titres de participation", source: "map" },
  { number: "7722", label: "Revenus autres titres immobilisés", source: "map" },
  { number: "773", label: "Escomptes obtenus", source: "map" },
  { number: "774", label: "Revenus de placement", source: "map" },
  { number: "7745", label: "Revenus des obligations", source: "map" },
  { number: "7746", label: "Revenus des titres de placement", source: "map" },
  { number: "7747", label: "Revenus des dépôts à terme et opérations assimilées", source: "map" },
  { number: "7748", label: "Autres revenus de placement", source: "map" },
  { number: "776", label: "Gains de change financiers", source: "map" },
  { number: "777", label: "Gains sur cessions de titres de placement", source: "map" },
  { number: "778", label: "Gains sur risques financiers", source: "map" },
  { number: "7781", label: "Gains sur rentes viagéres", source: "map" },
  { number: "7782", label: "Gains sur opérations financières", source: "map" },
  {
    number: "779",
    label:
      "Reprises de charges pour dépréciations et provisions pour risques à court terme financières",
    source: "map",
  },
  { number: "7791", label: "Reprises de provisions sur risques financiers", source: "map" },
  {
    number: "7795",
    label: "Reprises de charges pour dépréciations sur titres de placement",
    source: "map",
  },
  {
    number: "7798",
    label:
      "Autres reprises de charges pour dépréciations et provisions pour risques à court terme financières",
    source: "map",
  },
  { number: "78", label: "TRANSFERTS DE CHARGES", source: "map" },
  { number: "781", label: "Transferts de charges d’exploitation", source: "map" },
  { number: "787", label: "Transferts de charges financières", source: "map" },
  { number: "79", label: "REPRISES DE PROVISIONS, DE DEPRECIATIONS ET AUTRES", source: "map" },
  { number: "791", label: "Reprises de provisions et dépréciations d'exploitation", source: "map" },
  { number: "7911", label: "Reprises de provisions pour risques et charges", source: "map" },
  {
    number: "7913",
    label: "Reprises de dépréciations des immobilisations incorporelles",
    source: "map",
  },
  {
    number: "7914",
    label: "Reprises de dépréciations des immobilisations corporelles",
    source: "map",
  },
  {
    number: "792",
    label: "Reprises de fonds affectés et provenant des dons et legs d’immobilisations",
    source: "map",
  },
  {
    number: "7923",
    label: "Reprises de fonds affectés provenant de dons et legs d’immobilisations",
    source: "map",
  },
  { number: "7925", label: "Reprises de fonds affectés à un projet spécifique", source: "map" },
  { number: "7928", label: "Autres reprises de fonds affectés", source: "map" },
  {
    number: "795",
    label:
      "Reprises des dépréciations d’immobilisations reçues destinées à la vente provenant des dons et legs et d’usufruit temporaire",
    source: "map",
  },
  { number: "7951", label: "Reprises des dépréciations d’usufruit temporaire", source: "map" },
  {
    number: "7952",
    label:
      "Reprises des dépréciations d’immobilisations reçues destinées à la vente provenant des dons et legs",
    source: "map",
  },
  { number: "796", label: "Reprises des fonds reportés", source: "map" },
  {
    number: "7961",
    label: "Reprises de fonds reportés provenant de la donation temporaire d’usufruit",
    source: "map",
  },
  {
    number: "7962",
    label:
      "Reprises de fonds reportés provenant de dons et legs d’immobilisations reçues destinées à la vente",
    source: "map",
  },
  { number: "7968", label: "Autres reprises de fonds reportés", source: "map" },
  { number: "797", label: "Reprises de provisions et dépréciations financiéres", source: "map" },
  { number: "7971", label: "Reprises de provisions pour risques et charges", source: "map" },
  {
    number: "7972",
    label: "Reprises de dépréciations des immobilisations financières",
    source: "map",
  },
  { number: "798", label: "Reprises d’amortissements", source: "map" },
  { number: "799", label: "Reprises de subventions d’investissement", source: "map" },
  { number: "81", label: "VALEURS COMPTABLES DES CESSIONS D’IMMOBILISATIONS", source: "map" },
  {
    number: "811",
    label: "Valeurs comptables des cessions d’immobilisations incorporelles",
    source: "map",
  },
  {
    number: "812",
    label: "Valeurs comptables des cessions d’immobilisations corporelles",
    source: "map",
  },
  {
    number: "816",
    label: "Valeurs comptables des cessions d’immobilisations financières",
    source: "map",
  },
  {
    number: "818",
    label:
      "Valeurs comptables des cessions d’immobilisations reçues destinées à la vente provenant de dons et legs",
    source: "map",
  },
  { number: "82", label: "PRODUITS DES CESSIONS D’IMMOBILISATIONS", source: "map" },
  { number: "821", label: "Produits des cessions d’immobilisations incorporelles", source: "map" },
  { number: "822", label: "Produits des cessions d’immobilisations corporelles", source: "map" },
  { number: "826", label: "Produits des cessions d’immobilisations financières", source: "map" },
  {
    number: "828",
    label:
      "Produits des cessions d’immobilisations reçues destinées à la vente provenant de dons et legs",
    source: "map",
  },
  { number: "83", label: "CHARGES HORS ACTIVITES ORDINAIRES", source: "map" },
  { number: "831", label: "Charges H.A.O. constatées", source: "map" },
  { number: "8311", label: "Dons en nature H.A.O. non affectés", source: "map" },
  { number: "8315", label: "Dons en nature H.A.O. affectés", source: "map" },
  { number: "832", label: "Dons en nature H.A.O. à distribuer", source: "map" },
  { number: "834", label: "Pertes sur créances H.A.O.", source: "map" },
  { number: "836", label: "Abandons de créances consentis", source: "map" },
  { number: "838", label: "Transferts de charges H.A.O.", source: "map" },
  {
    number: "839",
    label: "Charges pour dépréciations et provisions pour risques à court terme H.A.O.",
    source: "map",
  },
  { number: "84", label: "REVENUS HORS ACTIVITES ORDINAIRES", source: "map" },
  { number: "841", label: "Produits H.A.O. constatés", source: "map" },
  { number: "8411", label: "Dons en nature HAO vendus", source: "map" },
  { number: "8412", label: "Prestations de services en nature HAO", source: "map" },
  { number: "8415", label: "Dons en nature HAO à distribuer", source: "map" },
  { number: "842", label: "Contributions volontaires en nature", source: "map" },
  { number: "843", label: "Contributions volontaires en numéraire", source: "map" },
  { number: "846", label: "Abandons de créances obtenus", source: "map" },
  { number: "848", label: "Transferts de produits H.A.O", source: "map" },
  {
    number: "849",
    label: "Reprises de charges pour dépréciations et provisions pour risques à court terme",
    source: "map",
  },
  { number: "85", label: "DOTATIONS HORS ACTIVITES ORDINAIRES", source: "map" },
  { number: "851", label: "Dotations aux provisions réglementées", source: "map" },
  { number: "852", label: "Dotations aux amortissements H.A.O,", source: "map" },
  { number: "853", label: "Dotations aux dépréciations H.A.O.", source: "map" },
  {
    number: "854",
    label: "Dotations aux provisions pour risques et charges H.A.O.",
    source: "map",
  },
  { number: "858", label: "Autres dotations H.A.O", source: "map" },
  {
    number: "86",
    label: "REPRISES D'AMORTISSEMENTS, PROVISIONS ET DEPRECIATIONS HAO.",
    source: "map",
  },
  { number: "861", label: "Reprises de provisions réglementées", source: "map" },
  { number: "862", label: "Reprises d’amortissements H.A.O.", source: "map" },
  { number: "863", label: "Reprises de dépréciations H.A.O.", source: "map" },
  { number: "864", label: "Reprises de provisions pour risques et charges H.A.O.", source: "map" },
  { number: "868", label: "Autres reprises H.A.O.", source: "map" },
  { number: "87", label: "VARIATIONS DE STOCKS DE DONS EN NATURE HAO", source: "map" },
  { number: "88", label: "SUBVENTIONS D'ÉQUILIBRE", source: "map" },
  { number: "881", label: "Subventions d’équilibre, État", source: "map" },
  { number: "884", label: "Subventions d’équilibre, Collectivités publiques", source: "map" },
  { number: "888", label: "Autres subventions d’équilibre", source: "map" },
  { number: "90", label: "EMPLOIS DES CONTRIBUTIONS VOLONTAIRES EN NATURE", source: "map" },
  { number: "900", label: "Secours en nature", source: "map" },
  { number: "901", label: "Mises à disposition gratuite de biens", source: "map" },
  { number: "902", label: "Prestations en nature", source: "map" },
  { number: "904", label: "Personnel bénévole", source: "map" },
  { number: "91", label: "CONTRIBUTIONS VOLONTAIRES EN NATURE", source: "map" },
  { number: "910", label: "Dons en nature", source: "map" },
  { number: "911", label: "Prestations en nature", source: "map" },
  { number: "914", label: "Bénévolat", source: "map" },
  { number: "92", label: "COMPTES REFLECHIS", source: "map" },
  { number: "93", label: "COMPTES DE RECLASSEMENTS", source: "map" },
  { number: "94", label: "COMPTES DE COÛTS", source: "map" },
  { number: "95", label: "COMPTES DE STOCKS", source: "map" },
  { number: "96", label: "COMPTES D’ÉCARTS SUR COÛTS PRÉÉTABLIS", source: "map" },
  { number: "97", label: "COMPTES DE DIFFÉRENCES DE TRAITEMENT COMPTABLE", source: "map" },
  { number: "98", label: "COMPTES DE RESULTATS", source: "map" },
  { number: "99", label: "COMPTES DE LIAISONS INTERNES", source: "map" },
];
